services:
  server1:
    command:
      - python
      - -u
      - -m
      - nvflare.private.fed.app.server.server_train
      - -m
      - /workspace
      - -s
      - fed_server.json
      - --set
      - secure_train=true
      - config_folder=config
      - org=nvidia
    container_name: server1
    image: fl-manager:dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    ports:
      - "8002:8002"
      - "8003:8003"
    volumes:
      - ../../:/opt/project
      - ./workspace/example_project/prod_00/server1:/workspace
      - nvflare_svc_persist:/tmp/nvflare/
  site-1:
    command:
      - python
      - -u
      - -m
      - nvflare.private.fed.app.client.client_train
      - -m
      - /workspace
      - -s
      - fed_client.json
      - --set
      - secure_train=true
      - uid=site-1
      - org=nvidia
      - config_folder=config
    container_name: site-1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    image: fl-manager:dev
    volumes:
      - ../../:/opt/project
      - ./workspace/example_project/prod_00/site-1:/workspace
  site-2:
    command:
      - python
      - -u
      - -m
      - nvflare.private.fed.app.client.client_train
      - -m
      - /workspace
      - -s
      - fed_client.json
      - --set
      - secure_train=true
      - uid=site-2
      - org=nvidia
      - config_folder=config
    container_name: site-2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    image: fl-manager:dev
    volumes:
      - ../../:/opt/project
      - ./workspace/example_project/prod_00/site-2:/workspace
volumes:
  nvflare_svc_persist: null
